{site-description}.

This plugin has the following features:

1. link:examples/run.html[Running in development mode].
2. link:examples/package.html[Packaging] an application into different formats: fat JAR, native image, Docker, etc.
3. link:dockerfile-mojo.html[Generating `Dockerfile`]s.
4. link:examples/deploy.html[Deploying] Docker images to different registries.
5. link:examples/aot.html[Using Micronaut AOT].
6. link:examples/test-resources.html[Integration with Micronaut Test Resources].
7. link:examples/openapi.html[Integration with Micronaut OpenAPI].
8. link:examples/bean-import.html[Importing beans from project dependencies].
9. link:examples/jsonschema.html[Generating Sources from JSON Schema]

=== Usage

It is recommended to use this plugin in combination with the https://central.sonatype.com/artifact/io.micronaut.platform/micronaut-parent[Micronaut Parent POM].

Then, declare the plugin to your `build/plugins` section:

[source,xml,subs="verbatim,attributes"]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!-- ... -->
    <packaging>${packaging}</packaging>

    <properties>
        <!-- ... -->
        <packaging>jar</packaging>
        <micronaut.runtime>netty</micronaut.runtime>
    </properties>

    <build>
        <plugins>
            <!-- ... -->

            <plugin>
                <groupId>io.micronaut.maven</groupId>
                <artifactId>micronaut-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
----

WARNING: Since version 4.0.0 of this plugin (which is the version compatible with Micronaut 4.x), the group id is
`io.micronaut.maven`. Earlier versions compatible with Micronaut 3.x used `io.micronaut.build`.

The `<packaging>` part is important since the plugin support several packaging types. The default is `jar`.

For snapshot versions, you need the Maven Central Portal Snapshot repository:

[source,xml]
----
<project>

    <!-- ... -->

    <pluginRepositories>

        <!-- ... -->

        <pluginRepository>
            <id>central-portal-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
</project>
----
